# Generated by Django 5.1 on 2024-08-29 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='Название новости')),
                ('after', models.CharField(max_length=100, verbose_name='Автор')),
                ('short_description', models.CharField(max_length=250, verbose_name='Краткое описание')),
                ('text', models.TextField(verbose_name='Новость')),
                ('pab_data', models.DateTimeField(verbose_name='Дата публикации')),
            ],
        ),
    ]
